---
- hosts: solr
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: Restart Solr.
      service:
        name: solr
        state: restarted

  tasks:
    - name: Install Java.
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Download Solr.
      get_url:
        url: "http://apache.cs.uu.nl/lucene/solr/{{solr_version}}/solr-{{solr_version}}.tgz"
        dest: "{{download_dir}}/solr-{{solr_version}}.tgz"
        checksum: "{{solr_checksum}}"

    - name: Expand Solr.
      unarchive:
        src: "{{download_dir}}/solr-{{solr_version}}.tgz"
        dest: "{{download_dir}}"
        remote_src: true
        creates: "{{download_dir}}/solr-{{solr_version}}/README.txt"

    - name: Execute Solr installation sh.
      command: >
        {{download_dir}}/solr-{{solr_version}}/bin/install_solr_service.sh
        {{download_dir}}/solr-{{solr_version}}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{solr_dir}}/bin/solr

    - name: Ensure Solr is started and enabled on boot.
      service:
        name: solr
        state: started
        enabled: true
